/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesModuleSlugSectionSlugRouteImport } from './routes/modules.$moduleSlug.$sectionSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleSlugSectionSlugRoute =
  ModulesModuleSlugSectionSlugRouteImport.update({
    id: '/modules/$moduleSlug/$sectionSlug',
    path: '/modules/$moduleSlug/$sectionSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules/$moduleSlug/$sectionSlug': typeof ModulesModuleSlugSectionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules/$moduleSlug/$sectionSlug': typeof ModulesModuleSlugSectionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules/$moduleSlug/$sectionSlug': typeof ModulesModuleSlugSectionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modules/$moduleSlug/$sectionSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modules/$moduleSlug/$sectionSlug'
  id: '__root__' | '/' | '/modules/$moduleSlug/$sectionSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesModuleSlugSectionSlugRoute: typeof ModulesModuleSlugSectionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleSlug/$sectionSlug': {
      id: '/modules/$moduleSlug/$sectionSlug'
      path: '/modules/$moduleSlug/$sectionSlug'
      fullPath: '/modules/$moduleSlug/$sectionSlug'
      preLoaderRoute: typeof ModulesModuleSlugSectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesModuleSlugSectionSlugRoute: ModulesModuleSlugSectionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
