import type { ModuleDef } from "../../types";

export const tanstackRouterModule: ModuleDef = {
  slug: "tanstack-router",
  track: "frontend",
  orderIndex: 1,
  title: "Tanstack Router",
  summary: "File-based routing, type-safe params, loaders, and the production patterns a startup team actually ships.",
  estMinutes: 221,
  sections: [
    {
      slug: "why",
      title: "Why Tanstack Router exists",
      kind: "why",
      estMinutes: 8,
      bodyMdxPath: "modules/tanstack-router/sections/why.mdx",
    },
    {
      slug: "file-based-routing",
      title: "File-based routing",
      kind: "concept",
      estMinutes: 12,
      bodyMdxPath: "modules/tanstack-router/sections/file-based-routing.mdx",
    },
    {
      slug: "loaders-and-data",
      title: "Loaders and data flow",
      kind: "concept",
      estMinutes: 14,
      bodyMdxPath: "modules/tanstack-router/sections/loaders-and-data.mdx",
    },
    {
      slug: "type-safe-params",
      title: "Type-safe params and search",
      kind: "pattern",
      estMinutes: 10,
      bodyMdxPath: "modules/tanstack-router/sections/type-safe-params.mdx",
    },
    {
      slug: "tradeoffs",
      title: "Tradeoffs vs the alternatives",
      kind: "tradeoff",
      estMinutes: 8,
      bodyMdxPath: "modules/tanstack-router/sections/tradeoffs.mdx",
    },
    {
      slug: "gotchas",
      title: "Production gotchas",
      kind: "gotcha",
      estMinutes: 9,
      bodyMdxPath: "modules/tanstack-router/sections/gotchas.mdx",
    },
    {
      slug: "mini-project",
      title: "Typed routing demo",
      kind: "mini_project",
      estMinutes: 150,
      bodyMdxPath: "modules/tanstack-router/sections/mini-project.mdx",
    },
    {
      slug: "quiz",
      title: "Self-check",
      kind: "quiz",
      estMinutes: 6,
      bodyMdxPath: "modules/tanstack-router/sections/quiz.mdx",
    },
    {
      slug: "cheatsheet",
      title: "Cheatsheet",
      kind: "cheatsheet",
      estMinutes: 4,
      bodyMdxPath: "modules/tanstack-router/sections/cheatsheet.mdx",
    },
  ],
};
